/**
 * 用于定义Action 常量
 */

const INCREMENT = 'INCREMENT'
const DECREMENT = 'DECREMENT'
const INCREMENT_ASYNC = 'INCREMENT_ASYNC'
const ADD_PERSON = 'ADD_PERSON'


export { INCREMENT, DECREMENT, INCREMENT_ASYNC, ADD_PERSON }
